// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order defines sort order for query results.
type Order int32

const (
	Order_ORDER_DESC Order = 0
	Order_ORDER_ASC  Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_DESC",
		1: "ORDER_ASC",
	}
	Order_value = map[string]int32{
		"ORDER_DESC": 0,
		"ORDER_ASC":  1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

// LogEntry represents a single log record.
type LogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampNanos int64                  `protobuf:"varint,2,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	Namespace      string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod            string                 `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	Container      string                 `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	Severity       uint32                 `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Message        string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEntry) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

func (x *LogEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogEntry) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogEntry) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogEntry) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// WriteRequest contains log entries to persist.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// WriteResponse contains the result of a write operation.
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// QueryRequest contains search criteria for log entries.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time range (start inclusive, end exclusive).
	StartTimeNanos int64 `protobuf:"varint,1,opt,name=start_time_nanos,json=startTimeNanos,proto3" json:"start_time_nanos,omitempty"`
	EndTimeNanos   int64 `protobuf:"varint,2,opt,name=end_time_nanos,json=endTimeNanos,proto3" json:"end_time_nanos,omitempty"`
	// Full-text search on message body.
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	// Kubernetes field filters (exact match).
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod       string `protobuf:"bytes,5,opt,name=pod,proto3" json:"pod,omitempty"`
	Container string `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	// Severity filter - returns entries >= this level.
	MinSeverity uint32 `protobuf:"varint,7,opt,name=min_severity,json=minSeverity,proto3" json:"min_severity,omitempty"`
	// Attribute filters (exact match, AND logic).
	Attributes map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Pagination controls.
	Limit         int32 `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	AfterId       int64 `protobuf:"varint,10,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	BeforeId      int64 `protobuf:"varint,11,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	Order         Order `protobuf:"varint,12,opt,name=order,proto3,enum=kubelogs.storage.v1.Order" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRequest) GetStartTimeNanos() int64 {
	if x != nil {
		return x.StartTimeNanos
	}
	return 0
}

func (x *QueryRequest) GetEndTimeNanos() int64 {
	if x != nil {
		return x.EndTimeNanos
	}
	return 0
}

func (x *QueryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *QueryRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *QueryRequest) GetMinSeverity() uint32 {
	if x != nil {
		return x.MinSeverity
	}
	return 0
}

func (x *QueryRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetAfterId() int64 {
	if x != nil {
		return x.AfterId
	}
	return 0
}

func (x *QueryRequest) GetBeforeId() int64 {
	if x != nil {
		return x.BeforeId
	}
	return 0
}

func (x *QueryRequest) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_DESC
}

// QueryResponse contains the results of a log query.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    int64                  `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	TotalEstimate int64                  `protobuf:"varint,4,opt,name=total_estimate,json=totalEstimate,proto3" json:"total_estimate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QueryResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *QueryResponse) GetTotalEstimate() int64 {
	if x != nil {
		return x.TotalEstimate
	}
	return 0
}

// GetByIDRequest requests a single log entry by ID.
type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetByIDResponse contains a single log entry.
type GetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDResponse) Reset() {
	*x = GetByIDResponse{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDResponse) ProtoMessage() {}

func (x *GetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetByIDResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIDResponse) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// DeleteRequest specifies entries to delete by age.
type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OlderThanNanos int64                  `protobuf:"varint,1,opt,name=older_than_nanos,json=olderThanNanos,proto3" json:"older_than_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetOlderThanNanos() int64 {
	if x != nil {
		return x.OlderThanNanos
	}
	return 0
}

// DeleteResponse contains the result of a delete operation.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// StatsRequest requests storage statistics.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

// StatsResponse contains storage statistics.
type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries     int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	DiskSizeBytes    int64                  `protobuf:"varint,2,opt,name=disk_size_bytes,json=diskSizeBytes,proto3" json:"disk_size_bytes,omitempty"`
	OldestEntryNanos int64                  `protobuf:"varint,3,opt,name=oldest_entry_nanos,json=oldestEntryNanos,proto3" json:"oldest_entry_nanos,omitempty"`
	NewestEntryNanos int64                  `protobuf:"varint,4,opt,name=newest_entry_nanos,json=newestEntryNanos,proto3" json:"newest_entry_nanos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *StatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *StatsResponse) GetDiskSizeBytes() int64 {
	if x != nil {
		return x.DiskSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetOldestEntryNanos() int64 {
	if x != nil {
		return x.OldestEntryNanos
	}
	return 0
}

func (x *StatsResponse) GetNewestEntryNanos() int64 {
	if x != nil {
		return x.NewestEntryNanos
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x13kubelogs.storage.v1\"\xd5\x02\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0ftimestamp_nanos\x18\x02 \x01(\x03R\x0etimestampNanos\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\tR\tcontainer\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\rR\bseverity\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12M\n" +
	"\n" +
	"attributes\x18\b \x03(\v2-.kubelogs.storage.v1.LogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\fWriteRequest\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.kubelogs.storage.v1.LogEntryR\aentries\"%\n" +
	"\rWriteResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\xf9\x03\n" +
	"\fQueryRequest\x12(\n" +
	"\x10start_time_nanos\x18\x01 \x01(\x03R\x0estartTimeNanos\x12$\n" +
	"\x0eend_time_nanos\x18\x02 \x01(\x03R\fendTimeNanos\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x05 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\x12!\n" +
	"\fmin_severity\x18\a \x01(\rR\vminSeverity\x12Q\n" +
	"\n" +
	"attributes\x18\b \x03(\v21.kubelogs.storage.v1.QueryRequest.AttributesEntryR\n" +
	"attributes\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\x12\x19\n" +
	"\bafter_id\x18\n" +
	" \x01(\x03R\aafterId\x12\x1b\n" +
	"\tbefore_id\x18\v \x01(\x03R\bbeforeId\x120\n" +
	"\x05order\x18\f \x01(\x0e2\x1a.kubelogs.storage.v1.OrderR\x05order\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\rQueryResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.kubelogs.storage.v1.LogEntryR\aentries\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\x03R\n" +
	"nextCursor\x12%\n" +
	"\x0etotal_estimate\x18\x04 \x01(\x03R\rtotalEstimate\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x0fGetByIDResponse\x123\n" +
	"\x05entry\x18\x01 \x01(\v2\x1d.kubelogs.storage.v1.LogEntryR\x05entry\"9\n" +
	"\rDeleteRequest\x12(\n" +
	"\x10older_than_nanos\x18\x01 \x01(\x03R\x0eolderThanNanos\"5\n" +
	"\x0eDeleteResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\"\x0e\n" +
	"\fStatsRequest\"\xb8\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12&\n" +
	"\x0fdisk_size_bytes\x18\x02 \x01(\x03R\rdiskSizeBytes\x12,\n" +
	"\x12oldest_entry_nanos\x18\x03 \x01(\x03R\x10oldestEntryNanos\x12,\n" +
	"\x12newest_entry_nanos\x18\x04 \x01(\x03R\x10newestEntryNanos*&\n" +
	"\x05Order\x12\x0e\n" +
	"\n" +
	"ORDER_DESC\x10\x00\x12\r\n" +
	"\tORDER_ASC\x10\x012\xa9\x03\n" +
	"\x0eStorageService\x12N\n" +
	"\x05Write\x12!.kubelogs.storage.v1.WriteRequest\x1a\".kubelogs.storage.v1.WriteResponse\x12N\n" +
	"\x05Query\x12!.kubelogs.storage.v1.QueryRequest\x1a\".kubelogs.storage.v1.QueryResponse\x12T\n" +
	"\aGetByID\x12#.kubelogs.storage.v1.GetByIDRequest\x1a$.kubelogs.storage.v1.GetByIDResponse\x12Q\n" +
	"\x06Delete\x12\".kubelogs.storage.v1.DeleteRequest\x1a#.kubelogs.storage.v1.DeleteResponse\x12N\n" +
	"\x05Stats\x12!.kubelogs.storage.v1.StatsRequest\x1a\".kubelogs.storage.v1.StatsResponseB,Z*github.com/kubelogs/kubelogs/api/storagepbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_storage_proto_goTypes = []any{
	(Order)(0),              // 0: kubelogs.storage.v1.Order
	(*LogEntry)(nil),        // 1: kubelogs.storage.v1.LogEntry
	(*WriteRequest)(nil),    // 2: kubelogs.storage.v1.WriteRequest
	(*WriteResponse)(nil),   // 3: kubelogs.storage.v1.WriteResponse
	(*QueryRequest)(nil),    // 4: kubelogs.storage.v1.QueryRequest
	(*QueryResponse)(nil),   // 5: kubelogs.storage.v1.QueryResponse
	(*GetByIDRequest)(nil),  // 6: kubelogs.storage.v1.GetByIDRequest
	(*GetByIDResponse)(nil), // 7: kubelogs.storage.v1.GetByIDResponse
	(*DeleteRequest)(nil),   // 8: kubelogs.storage.v1.DeleteRequest
	(*DeleteResponse)(nil),  // 9: kubelogs.storage.v1.DeleteResponse
	(*StatsRequest)(nil),    // 10: kubelogs.storage.v1.StatsRequest
	(*StatsResponse)(nil),   // 11: kubelogs.storage.v1.StatsResponse
	nil,                     // 12: kubelogs.storage.v1.LogEntry.AttributesEntry
	nil,                     // 13: kubelogs.storage.v1.QueryRequest.AttributesEntry
}
var file_storage_proto_depIdxs = []int32{
	12, // 0: kubelogs.storage.v1.LogEntry.attributes:type_name -> kubelogs.storage.v1.LogEntry.AttributesEntry
	1,  // 1: kubelogs.storage.v1.WriteRequest.entries:type_name -> kubelogs.storage.v1.LogEntry
	13, // 2: kubelogs.storage.v1.QueryRequest.attributes:type_name -> kubelogs.storage.v1.QueryRequest.AttributesEntry
	0,  // 3: kubelogs.storage.v1.QueryRequest.order:type_name -> kubelogs.storage.v1.Order
	1,  // 4: kubelogs.storage.v1.QueryResponse.entries:type_name -> kubelogs.storage.v1.LogEntry
	1,  // 5: kubelogs.storage.v1.GetByIDResponse.entry:type_name -> kubelogs.storage.v1.LogEntry
	2,  // 6: kubelogs.storage.v1.StorageService.Write:input_type -> kubelogs.storage.v1.WriteRequest
	4,  // 7: kubelogs.storage.v1.StorageService.Query:input_type -> kubelogs.storage.v1.QueryRequest
	6,  // 8: kubelogs.storage.v1.StorageService.GetByID:input_type -> kubelogs.storage.v1.GetByIDRequest
	8,  // 9: kubelogs.storage.v1.StorageService.Delete:input_type -> kubelogs.storage.v1.DeleteRequest
	10, // 10: kubelogs.storage.v1.StorageService.Stats:input_type -> kubelogs.storage.v1.StatsRequest
	3,  // 11: kubelogs.storage.v1.StorageService.Write:output_type -> kubelogs.storage.v1.WriteResponse
	5,  // 12: kubelogs.storage.v1.StorageService.Query:output_type -> kubelogs.storage.v1.QueryResponse
	7,  // 13: kubelogs.storage.v1.StorageService.GetByID:output_type -> kubelogs.storage.v1.GetByIDResponse
	9,  // 14: kubelogs.storage.v1.StorageService.Delete:output_type -> kubelogs.storage.v1.DeleteResponse
	11, // 15: kubelogs.storage.v1.StorageService.Stats:output_type -> kubelogs.storage.v1.StatsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
